Toggle element selector modal sidebar for small screens and zoom
craftcms/cms pull request #11323
Opened 2022-05-25 22:11 UTC by gcamacho079

### Description
Resolves DEV-547

### Related issues

2022-05-26 20:46 UTC, gcamacho079 commented
Not quite ready for review yet, fixing a couple of things

2022-06-08 03:56 UTC, brandonkelly requested changes

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +        if (!this.$sidebarToggleBtn) this.buildSidebarToggleView();
Should probably be:
```suggestion
        if (!this.$sidebarToggleBtn || !this.$sidebarToggleBtn.length) {
            this.buildSidebarToggleView();
        }
```

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +        if (this.$sidebarToggleBtn) this.resetView();
Should probably be:

```suggestion
        if (this.$sidebarToggleBtn && this.$sidebarToggleBtn.length) {
            this.resetView();
        }
```

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (this.$mainHeader) {
Should probably be:

```suggestion
      if (this.$mainHeader && this.$mainHeader.length) {
```

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (this.$sidebarHeader) {
Should probably be:

```suggestion
      if (this.$sidebarHeader && this.$sidebarHeader.length) {
```

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (!this.$sidebarToggleBtn) return;
Should probably be:

```suggestion
      if (!this.$sidebarToggleBtn || !this.$sidebarToggleBtn.length) {
          return;
      }
```

2022-06-08 03:56 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (!this.$mainHeading) return;
Should probably be:

```suggestion
      if (!this.$mainHeading || !this.$mainHeading.length) {
          return;
      }
```

2022-06-08 17:03 UTC, gcamacho079 commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (this.$sidebarToggleBtn || !this.sidebarShouldBeHidden()) return;
@brandonkelly question about this update. I'm not using the jQuery `find` method to set this variable, so `this.$sidebarToggleBtn` should only ever be `null` or the element (as created via the `Craft.ui.createButton` method. Should I still check the length of the jQuery object in instances like this?

2022-06-08 22:38 UTC, brandonkelly commented on src/web/assets/cp/src/js/BaseElementSelectorModal.js
> +      if (this.$sidebarToggleBtn || !this.sidebarShouldBeHidden()) return;
Sorry yep this one is fine as-is!

2022-06-09 16:33 UTC, gcamacho079 commented
> this one [`this.$sidebarToggleBtn`] is fine as-is!

`this.$mainHeading`, `this.$mainHeader`, `this.$sidebarHeader` are not set using the `find` method so I think the PR is good to go without the requested changes, but let me know if I misunderstood!

2022-06-09 21:36 UTC, merged