Feature/disable preview button during save
craftcms/cms pull request #11895
Opened 2022-09-06 23:29 UTC by brianjhanson

### Description
Disables the preview button while a draft is saving in order to prevent the wrong field layout from showing when the preview opens. 

### Related issues
#11858

2022-09-07 20:10 UTC, gcamacho079 requested changes
@brianjhanson nice update! Just one change I'd like to suggest:

- For screen reader accessibility, the `aria-disabled` attribute is preferred over `disabled`. It requires the extra step of preventing clicks programmatically, but is otherwise a usability improvement since screen reader users are alerted that the button is there, just inactive at the moment.

I was torn about whether the disabled state should be applied to the button immediately upon saving instead of on Preview click — and having the `disablePreviewButton` called with the `beforeRun` event — but I do see the benefit of keeping it clickable while the new layout is loading.

2022-09-08 13:23 UTC, brianjhanson commented
Thanks @gcamacho079! I ended up removing the event listeners when the preview button is disabled but I'm not sure if that's going too far. Let me know if there's a better way to disable programatic clicks.

2022-09-08 16:17 UTC, gcamacho079 approved these changes
Looks good, @brianjhanson. An alternative to adding/removing the click listener would be to immediately exit the `openPreview` function if the button already has the `aria-disabled` attribute.

2022-09-08 17:47 UTC, brianjhanson commented
@brandonkelly just pushed up that change

2022-09-13 12:32 UTC, merged