Fill image transform setting
craftcms/cms pull request #12214
Opened 2022-10-27 19:31 UTC by brianjhanson

### Description
Adds an additional `fill` parameter to image transforms.

The value of `fill` must be either a hex value (3 or 6 digits) or the string `transparent`. 

When the transform mode is set to `fit` and a fill color is provided, the fill color will be used to fill any empty pixels surrounding the image so the final image size is always equal to the transform sized passed in. 

You can also use `position` in order to control where within the transform space the image should appear. 

Within the UI there's a new "Fill empty pixels" checkbox that will show or hide the color field for the fill. 

https://user-images.githubusercontent.com/1843073/198377492-ad4793a4-9cb5-4a9e-9469-8fb6df80e369.mp4

### Related issues
#8848

### To-Do
- [ ] Support for animated files (gif, webp)
- [ ] Make sure non-raster images don't break

2022-10-27 22:13 UTC, brianjhanson commented on src/controllers/ImageTransformsController.php
> +
I'm not wild about this, but I couldn't think of a better way to allow users to specify if they wanted the current behavior (image is sized proportionately to fit within a window) or the new behavior (image is placed within an area specified by the transform). 

In code, the fact that `fill` exists tells Craft which behavior to us, but in the UI a fill is always returned, and currently there's not a difference between no fill and a transparent one.

2022-10-27 22:13 UTC, brianjhanson commented on src/migrations/Install.php
> +            'fill' => $this->string(11)->null(),
length is 11 so `transparent` fits

2023-01-10 19:55 UTC, brandonkelly requested changes

2023-01-10 19:55 UTC, brandonkelly commented on src/base/Image.php
> +    abstract public function scaleToFit(?int $targetWidth, ?int $targetHeight, bool $scaleIfSmaller = true, string $position = 'center-center'): self;
Missing `@param` for `$position`

2023-01-10 19:55 UTC, brandonkelly commented on src/image/Raster.php
> +    public function scaleToFit(?int $targetWidth, ?int $targetHeight, bool $scaleIfSmaller = true, array|string $position = 'center-center'): self
`$position` has a different type declaration here than in the base class (`array|string` vs `string`).

2023-01-10 19:55 UTC, brandonkelly commented on src/base/Image.php
> +    abstract public function scaleToFit(?int $targetWidth, ?int $targetHeight, bool $scaleIfSmaller = true, string $position = 'center-center'): self;
Also if the fill stuff is exclusive to `Raster`, it feels weird to have `$position` defined here in the base class. Maybe `Raster` should just be defining its own `scaleToFitAndFill()` method that combines `scaleToFit()` and `setFill()`?

2023-01-30 23:30 UTC, brandonkelly commented
@brianjhanson This doesn’t seem to be working for me.

I created a transform with the following settings:

- **Mode:** Fit
- **Fill empty pixels:** ✅ 
- **Fill Color:** `#ff0000`
- **Width:** 300
- **Height:** 200
- **Quality:** Auto
- **Interlacing:** None
- **Image Format:** Auto

However when I output a 1200x394 image using this transform, the result is 300x99 without any red pixels. I would have expected it to end up as 300x200, with ~50 red pixels above and below the original image.

(`upscaleImages` is `false`.)

And separately, looks like there’s a bug when **Fill Color** is left blank: when you go back to the transform edit page, the input value is set to `#transparent`.

2023-02-01 16:37 UTC, brandonkelly requested changes
As discussed,

- [ ] Let’s introduce a new dedicated “Letterbox” transform mode for this, with “Fill Color” and “Gravity” settings. (Gravity should default to `center-center`.)
- [ ] All transforms should get a new “Upscale” setting, and the `upscaleImages` config setting should be used by default.

2023-02-02 20:31 UTC, brianjhanson commented
Just pushed some code to address the first half of this and wanted to jot down some notes before I forget. 

### Positioning
I went with "Position" instead of "Gravity" because that felt more straightforward. In Cloudinary world, Gravity is how they refer to a focal point, but we have established language for that. We could keep it as "Focal Point" here, but given how it behaves, I think "position" is a better description (and aligns with how to determine it programmatically). 

![CleanShot 2023-02-02 at 14 29 52](https://user-images.githubusercontent.com/1843073/216442755-f7f10663-0c8d-49fa-b08f-78bc0519129b.png)

I duplicated the field rather than just messing with it via JS because JS introduced some complications (translations, accessibility, etc.). It felt like just duplicating the field was better all around. 

### UI Update
![CleanShot 2023-02-02 at 14 18 21](https://user-images.githubusercontent.com/1843073/216440603-5a5ac665-b128-4631-9a8c-85de9c1fd095.png)

### Focal Points
If an image has a focal point set, we will do our best to put that point into the center. Some screenshots of how this behaves are below. 

**Focal point**
![CleanShot 2023-02-02 at 14 22 17](https://user-images.githubusercontent.com/1843073/216441389-6bbc1309-983b-4405-be4a-279f2b5e537f.png)

**Results in**
![CleanShot 2023-02-02 at 14 22 29](https://user-images.githubusercontent.com/1843073/216441394-3734b9db-298e-4445-8147-8e9a96743a6d.png)

2023-02-04 01:48 UTC, merged