Feature/cms 1274 UI attributes for element index cards view
craftcms/cms pull request #15283
Opened 2024-07-02 15:00 UTC by i-just

### Description
Adds the ability to add attributes to the element card view and specify the order in which all the selected fields and attributes should appear.

- added `src/base/ElementInterface::cardAttributes()`
- added `src/base/ElementInterface::defaultCardAttributes()`
- added `src/events/RegisterElementCardAttributesEvent`
- added `src/events/RegisterElementDefaultCardAttributesEvent`
- added `src/helpers/Cp::cardViewDesignerHtml()`
- added `src/models/FieldLayout->getCardView()`
- added `src/models/FieldLayout->setCardView()`
- added `src/models/FieldLayout->getCardBodyAttributes()`
- added `src/models/FieldLayout->getCardBodyElements()`

<img width="1051" alt="Screenshot 2024-07-02 at 16 37 24" src="https://github.com/craftcms/cms/assets/4500340/5669906c-f299-45de-a836-c23577ce6710">
<img width="1048" alt="Screenshot 2024-07-02 at 16 37 47" src="https://github.com/craftcms/cms/assets/4500340/42600a46-091a-43c2-b64a-5df50ec1ed5b">

### Related issues
[CMS-1274](https://linear.app/craftcms/issue/CMS-1274/ui-attributes-for-element-index-cards-view)

2024-09-24 21:04 UTC, gcamacho079 requested changes
@i-just I’ve added some items to the Notion page we used for the previous review.

2024-09-25 07:13 UTC, i-just commented
Thanks @gcamacho079! That’s all actioned now.

2024-11-02 16:09 UTC, brandonkelly requested changes
Looking really good!

Couple things:

- It’s not super intuitive that to add custom fields, you still have to press “Show in element cards” in the disclosure menu. Let’s just get rid of those actions and start showing card view checkboxes for **all** selected custom fields that implement `PreviewableFieldInterface`.
- Let’s update the checkbox select to use the new `SortableCheckboxSelect`.

2024-11-04 17:39 UTC, i-just commented
Thanks @brandonkelly! It's all done now.

2024-11-04 23:42 UTC, merged