Feature/cms 660 show read-only settings when `allowAdminChanges` is disabled
craftcms/cms pull request #16265
Opened 2024-12-03 14:20 UTC by i-just

### Description
Shows read-only settings when `allowAdminChanges` is disabled.

- switched `.revision-notice` to a generic `.content-notice` class so that the styles can be reused for other purposes too
- when admin changes are disallowed, the “Settings” main nav item and all the subpages (except for the plugin settings) are shown, with all the fields and forms being disabled and with a notice at the top of every page
- plugins can opt into having their settings shown when `allowAdminChanges` is disabled; to do so, they need to ensure none of the settings are editable in such case and implement `public function canViewReadOnlySettings(): bool;` to return true
- `src/events/RegisterCpSettingsEvent` has a new public property `$readOnlyModeReady`, which is set to false by default; if the settings changes manipulated via the event are ready to be displayed in a non-editable way, set it to `true` to have them show when admin changes are not allowed.

<img width="1224" alt="Screenshot 2024-12-03 at 14 16 55" src="https://github.com/user-attachments/assets/acb99429-2dc1-48a8-b8f3-e893e8cd43d0">

### Related issues
[cms-660](https://linear.app/craftcms/issue/CMS-660/show-read-only-settings-when-allowadminchanges-==-false)

2024-12-04 13:21 UTC, Mosnar commented
Love this! It might be worth adding a "Learn More" button to a KB article explaining why settings can't/shouldn't be changed in production. Newer Craft developers or over-confident clients might read the current disclaimer as instructions to simply turn on "allowAdminChanges" and potentially get themselves in a mess.

2024-12-07 00:33 UTC, gcamacho079 requested changes
@i-just awesome! I pinged you on the Notion page for this feature as I had some follow-up questions.

2024-12-09 14:46 UTC, i-just commented
thanks @gcamacho079! I actioned all your comments. Extra info on the Notion page. LMK if anything doesn't make sense.

2024-12-15 21:27 UTC, gcamacho079 commented
Thanks for knocking out those changes, @i-just! A couple more things I noticed that should also get the `disabled` attribute:

- [ ] The `.menubtn` for “Selectable {{ element }} condition” on Entries and Assets field settings pages
- [ ] The “Static Rows” field (and the conditionally-revealed fields) on Table field settings
- [ ] Info toggle buttons inside disabled table fields (for example, in the “Site Settings” table heading on the Matrix field settings page)

2025-01-07 23:50 UTC, brandonkelly commented on src/helpers/Cp.php
> +            'disabled' => true,
@i-just What’s the reason for this?

2025-01-08 00:12 UTC, brandonkelly commented
I [changed things up a bit](https://github.com/craftcms/cms/pull/16265/commits/1a81b86c1a03fabd2ef0870adb15d6581a9f25a3) so now all configurable components have a `getReadOnlySettingsHtml()` method, which by default will return the same thing as `getSettingsHtml()` except with all inputs disabled (similar to `Field::getStaticHtml()`).

Fields, filesystems, and mail transport adapters now override `getReadOnlySettingsHtml()` whenever possible, with the exception of `BaseOptionsField` and `BaseRelationField` and their subclasses, as well as `Link` fields + link type classes (since in those cases, there’s no way to explicitly override `getReadOnlySettingsHtml()` without leaving 3rd party classes in the dust, so it’s better to wait until v6 before updating those).

Plugins similarly now have a `getReadOnlySettingsResponse()` method, and a `$hasReadOnlyCpSettings` property. `craft\base\Plugin::getReadOnlySettingsResponse()` will return `$this->getSettingsResponse()` with inputs in the settings HTML disabled (like `ConfigurableComponent::getReadOnlySettingsHtml()` and `Field::getStaticHtml()`), and its `init()` method will automatically set `$this->hasReadOnlyCpSettings = true` if `getSettingsResponse()` hasn’t been overridden.

The point of these changes is to limit the need to check `allowAdminChanges`, in case there’s a reason to render any of these settings without taking `allowAdminChanges` into effect. For example, a form plugin might have a need to render a Plain Text field’s settings even when `allowAdminChanges` is disabled (because maybe the field isn’t getting saved to the project config), and should still be able to call `$field->getSettingsHtml()` and get the normal non-disabled response.

2025-01-08 09:53 UTC, i-just commented on src/helpers/Cp.php
> +            'disabled' => true,
It was adding a `disabled` attribute to the fields inside the field layout designer’s `.fld-field-library`. But with the changes from https://github.com/craftcms/cms/pull/16374, it’s no longer needed (plus, it looks like I forgot to make it dynamic). I took that out.

2025-01-08 18:47 UTC, merged